all_atoms: false
atom_max_neighbors: 4
atom_radius: 3
backbone_loss_weight: 0
batch_size: 24
bootstrap_alpha: 1
bootstrap_beta: 1
bootstrap_tmin: 0
c_alpha_max_neighbors: 8
cache_path: data/cache
chain_cutoff: null
combined_training: false
confidence_mode: false
confidence_weight: 0.33
config: test_training_multi_gpu.yml
crop_beyond: 20
cross_distance_embed_dim: 16
cross_max_distance: 80
cudnn_benchmark: true
dataloader_drop_last: true
dataset: pdbbind
depthwise_convolution: false
device: cuda:0
dist_backend: nccl
dist_url: env://
distance_embed_dim: 16
distributed: true
double_val: false
dropout: 0.0
dynamic_max_cross: false
ema_rate: 0.999
embed_also_ligand: true
embedding_scale: 1000.0
embedding_type: sinusoidal
enforce_timesplit: false
esm_embeddings_model: null
freeze_params: 0
gpus: '0,1,2,3,4,5'
include_miscellaneous_atoms: false
inference_earlystop_goal: max
inference_earlystop_metric: valinf_min_rmsds_lt2
inference_samples: 1
inference_secondary_metric: null
inference_steps: 20
limit_complexes: 300
local_rank: 0
log_dir: workdir/spectral_dimension_fix
lr: 0.002
lr_start_factor: 0.001
max_lig_size: null
max_receptor_size: null
max_radius: 5.0
merge_clusters: 1
min_ligand_size: 0
model_type: spectral
moad_dir: ../data/BindingMOAD_2020_processed/
moad_esm_embeddings_path: null
moad_esm_embeddings_sequences_path: null
n_epochs: 200
no_aminoacid_identities: false
no_batch_norm: false
no_differentiate_convolutions: false
no_torsion: false
norm_by_sigma: false
not_fixed_knn_radius_graph: false
not_knn_only_graph: false
ns: 32
num_conf_gen_workers: 4
num_conformers: 1
num_conv_layers: 3
num_dataloader_workers: 8
num_inference_complexes: 200
num_prot_emb_layers: 0
num_workers: 6
nv: 8
odd_parity: false
pdbbind_dir: ../data/PDBBind_processed/
pdbbind_esm_embeddings_path: ../data/esm2_3billion_embeddings.pt
pdbbind_esm_embeddings_sequences_path: null
pin_memory: true
project: diffdock
protein_file: protein_processed
reduce_pseudoscalars: false
remove_hs: true
remove_promiscuous_targets: null
remove_second_segment: false
restart_dir: null
restart_ckpt: last_model
restart_lr: null
rot_sigma_max: 1.65
rot_sigma_min: 0.1
rot_weight: 0.33
run_name: multi_gpu_6x3090_training
sampling_alpha: 1
sampling_beta: 1
save_model_freq: 10
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 15
sh_lmax: 2
sidechain_loss_weight: 0
sigma_embed_dim: 32
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: false
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tp_weights_layers: 2
tr_sigma_max: 30
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
train_multiplicity: 1
triple_training: false
unroll_clusters: false
use_ema: true
use_old_atom_encoder: false
use_second_order_repr: false
use_simplified_complex: false
val_inference_freq: 5
val_multiplicity: 1
vandermers_buffer_residue_num: 7
vandermers_max_dist: 5
vandermers_min_contacts: null
w_decay: 0.0001
wandb: false
warmup_dur: 8
